import React from 'react'
import Post from "@/components/Post"
import CommentsBlock from "@/components/CommentsBlock"
import AddComment from "@/components/AddComment"
import PostSkeleton from "@/components/Post/Skeleton"
import {withRouter} from "next/router"
import {useGetPostByIdQuery} from "@/store/services/posts.api"
import ReactMarkdown from "react-markdown"
import {TRouter} from "@/types/general"
import Head from "next/head"
import {Divider} from "@mui/material"

const FullPost = ({router: {query}}: TRouter) => {
  const {id} = query as { id: string }
  const {data, isLoading} = useGetPostByIdQuery(id, {skip: !id, refetchOnMountOrArgChange: true})

  return (
    <>
      <Head>
        <title>Post page</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        {
          (isLoading || !data) ? <PostSkeleton/>
            :
            <Post
              _id={data._id}
              title={data.title}
              imageUrl={data.imageUrl}
              user={data.user}
              createdAt={data.createdAt}
              viewsCount={data.viewsCount}
              commentsCount={data.comments?.length}
              tags={data.tags}
              isFullPost
            >
              <ReactMarkdown children={data.text || ""}/>
            </Post>
        }
        <CommentsBlock
          items={data?.comments || []}
          isLoading={isLoading}
        >
          <Divider/>
          <AddComment postId={id}/>
        </CommentsBlock>
      </main>
    </>
  )
}

export default withRouter(FullPost)